- become: yes
  hosts: all
  name: apache-install
  tasks:
    - name: Install httpd
      yum: name=httpd update_cache=yes state=latest
      notify:
        - Restart httpd

  handlers:
    - name: Restart httpd
      service: name=httpd state=restarteds